version: "3.7"

services:
  city_db:
    image: centos/mysql-57-centos7
    networks:
      - city-network
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=city@@123456

  city-api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - city-network
    restart: on-failure
    depends_on:
      - city_db
    environment:
      - DATABASE_HOST=city_db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=city@@123456
      - DATABASE_NAME=citypreprod_db
      - DATABASE_PORT=3306
      - SPRING_SERVER_PORT=8080

networks:
  city-network:
    driver: bridge